CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,
  email VARCHAR(254) NOT NULL UNIQUE,
  name VARCHAR(200) NOT NULL DEFAULT '',
  passwordHash VARCHAR(255) NOT NULL,
  verified BOOLEAN NOT NULL DEFAULT FALSE,
  created DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tradingAccounts (
  id VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,
  userId VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  accountName VARCHAR(200) NOT NULL,
  startingBalance DECIMAL(20,6) NOT NULL,
  currency CHAR(3) NOT NULL DEFAULT 'EUR',
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  created DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY account_owner (id, userId), KEY account_user_created (userId, created),
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS trades (
  id VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,
  userId VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  accountId VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  symbol VARCHAR(30) NOT NULL,
  entryDate DATE NOT NULL, entryTime VARCHAR(5) NOT NULL,
  setup VARCHAR(80) NOT NULL DEFAULT '', side VARCHAR(5) NOT NULL DEFAULT '',
  riskAmount DECIMAL(20,6) NULL, profitLoss DECIMAL(20,6) NULL,
  fees DECIMAL(20,6) NULL DEFAULT 0, commissionPercentage DECIMAL(12,6) NULL DEFAULT 0,
  stopLoss DECIMAL(12,6) NULL, stopLossPips DECIMAL(20,6) NULL,
  rrSecured DECIMAL(20,6) NULL, riskRewardRatio DECIMAL(20,6) NULL,
  status VARCHAR(20) NOT NULL DEFAULT '',
  notes TEXT NOT NULL, contextUrl TEXT NOT NULL, validationUrl TEXT NOT NULL, entryUrl TEXT NOT NULL,
  reviewStatus VARCHAR(10) NOT NULL DEFAULT '', reviewSetup VARCHAR(3) NOT NULL DEFAULT '', reviewRisk VARCHAR(3) NOT NULL DEFAULT '',
  reviewTags JSON NOT NULL, reviewLesson TEXT NOT NULL, reviewAction TEXT NOT NULL, reviewCompletedAt DATETIME(3) NULL,
  importFingerprint CHAR(64) CHARACTER SET ascii NULL,
  created DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  KEY trade_user_date (userId, entryDate, entryTime, id),
  KEY trade_account_date (userId, accountId, entryDate, entryTime, id),
  KEY trade_review (userId, reviewStatus, entryDate),
  UNIQUE KEY trade_import (userId, importFingerprint),
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (accountId, userId) REFERENCES tradingAccounts(id, userId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS userSettings (
  id VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,
  userId VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL UNIQUE,
  startingBalance DECIMAL(20,6) NOT NULL DEFAULT 10000,
  commissionPercentage DECIMAL(12,6) NOT NULL DEFAULT 0,
  theme VARCHAR(5) NOT NULL DEFAULT 'dark',
  created DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS symbols (
  id VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,
  userId VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  symbol VARCHAR(30) NOT NULL,
  created DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY symbol_user (userId, symbol),
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS cookieConsent (
  id VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,
  userId VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL UNIQUE,
  consentGiven BOOLEAN NOT NULL, preferences TEXT NOT NULL,
  created DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sessions (
  tokenHash CHAR(64) CHARACTER SET ascii PRIMARY KEY,
  userId VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  expiresAt DATETIME(3) NOT NULL,
  KEY session_user (userId), KEY session_expiry (expiresAt),
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS actionTokens (
  tokenHash CHAR(64) CHARACTER SET ascii PRIMARY KEY,
  userId VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  purpose VARCHAR(12) NOT NULL, expiresAt DATETIME(3) NOT NULL,
  UNIQUE KEY action_user (userId, purpose), KEY action_expiry (expiresAt),
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS rateLimits (
  bucket CHAR(64) CHARACTER SET ascii PRIMARY KEY,
  hits INT UNSIGNED NOT NULL,
  expiresAt DATETIME(3) NOT NULL,
  KEY rate_expiry (expiresAt)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
