import React,{useState,useEffect} from 'react';
import {Link,useLocation,useNavigate} from 'react-router-dom';
import {MailCheck} from 'lucide-react';
import {useAuth} from '@/contexts/AuthContext';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import AuthLayout from '@/components/journal/AuthLayout';
export default function VerifyPendingPage(){
const auth=useAuth(),location=useLocation(),navigate=useNavigate(),token=new URLSearchParams(location.search).get('token');
const [email,setEmail]=useState(location.state?.email||auth.verificationEmail||''),[busy,setBusy]=useState(false),[cooldown,setCooldown]=useState(0),[error,setError]=useState(''),[requested,setRequested]=useState(location.state?.mailRequested);
useEffect(()=>{if(!cooldown)return;const t=setTimeout(()=>setCooldown(c=>c-1),1000);return()=>clearTimeout(t);},[cooldown]);
async function resend(e){e.preventDefault();setBusy(true);setError('');try{await auth.resendVerificationEmail(email.trim());setRequested(true);setCooldown(60);}catch{setError('Der Versand konnte nicht angefordert werden. Bitte versuche es später erneut.');}finally{setBusy(false);}}
async function confirm(){setBusy(true);setError('');try{const result=await auth.verifyAndAutoLogin(token);navigate(result?.record?.verified?'/home':'/login',{replace:true,state:{verified:true}});}catch{setError('Der Link ist ungültig oder abgelaufen. Fordere bitte einen neuen an.');}finally{setBusy(false);}}
return <AuthLayout title={token?'Bestätigung abschließen.':'Bestätige deine E-Mail.'} subtitle={token?'Ein letzter Schritt für den Zugang zu deinem Journal.':'Verwende die E-Mail-Adresse, mit der du dein Konto angelegt hast.'}><MailCheck className="text-primary mb-6" size={32}/>{token?<><Button onClick={confirm} disabled={busy} className="w-full">{busy?'Wird bestätigt…':'E-Mail bestätigen'}</Button>{error&&<p role="alert" className="mt-4 text-sm text-destructive">{error}</p>}<Link to="/verify-pending" className="block mt-5 text-sm text-primary">Neuen Link anfordern</Link></>:<form onSubmit={resend} className="space-y-5">{requested===false&&<p role="alert" className="text-sm text-accent">Dein Konto wurde erstellt, aber die Versand-Anfrage ist fehlgeschlagen. Du musst dich nicht erneut registrieren.</p>}{requested===true&&<p role="status" className="text-sm text-primary">Die Anfrage wurde angenommen. Falls die Adresse zu einem noch unbestätigten Konto gehört, wird eine E-Mail versendet. Prüfe auch den Spam-Ordner.</p>}<label className="form-field">E-Mail<Input type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label>{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}<Button className="w-full" disabled={busy||cooldown>0}>{busy?'Wird angefordert…':cooldown?'Erneut möglich in '+cooldown+' s':'Bestätigungslink anfordern'}</Button></form>}<p className="mt-6 text-sm text-muted-foreground">Bereits bestätigt? <Link to="/login" className="text-primary">Zur Anmeldung</Link></p></AuthLayout>;
}
