// Explanations describe the current calculations, not future trading outcomes.
export const metricHelp = {
  netPnl: {
    title: 'Netto-Ergebnis',
    meaning: 'Dein erfasstes Ergebnis nach Kosten im gewählten Zeitraum.',
    calculation: 'Summe aller Brutto-Ergebnisse minus Ordergebühren, Swap und Gewinnbeteiligung. Die Beteiligung wird nur auf positive Brutto-Ergebnisse angewendet.',
    reading: '+200 € bedeutet 200 € Nettogewinn, −200 € einen Nettoverlust. Offene Positionen und nicht erfasste Kosten fehlen in dieser Zahl.',
  },
  returnPct: {
    title: 'Netto-Ergebnis in Prozent',
    meaning: 'Setzt deinen Nettogewinn oder -verlust ins Verhältnis zum Kapital zu Beginn des Zeitraums.',
    calculation: 'Netto-Ergebnis ÷ Kapital am Zeitraumstart × 100. Bei mehreren Konten zählt das gemeinsame Startkapital.',
    reading: '+5 % entsprechen 500 € Gewinn bei 10.000 € Startkapital. Ohne positives Startkapital ist der Wert nicht berechenbar. Offene Positionen und nicht erfasste Ein- oder Auszahlungen bleiben unberücksichtigt.',
  },
  netR: {
    title: 'Netto-R',
    meaning: 'Macht Trades mit unterschiedlichen Geldbeträgen vergleichbar: 1 R entspricht dem ursprünglichen Geldrisiko eines Trades.',
    calculation: 'Netto-Ergebnis des Trades ÷ ursprüngliches Geldrisiko.',
    reading: 'Bei 100 € Risiko sind 150 € Nettogewinn +1,5 R; 100 € Nettoverlust sind −1 R. Fehlendes Risiko ergibt keinen R-Wert. Rekonstruktionen und Schätzungen sind nur so verlässlich wie ihre Grundlagen.',
  },
  expectancyR: {
    title: 'Erwartungswert in R',
    meaning: 'Zeigt, was ein Trade bisher im Durchschnitt relativ zu seinem ursprünglichen Risiko gebracht hat.',
    calculation: 'Für jeden Trade: Netto-Ergebnis ÷ Geldrisiko. Danach Summe dieser Netto-R ÷ Anzahl auswertbarer Trades. Fehlendes Risiko zählt nicht als 0 R.',
    reading: '+0,5 R bedeutet im Schnitt einen Nettogewinn in Höhe des halben Risikos; ein negativer Wert bedeutet einen durchschnittlichen Verlust. Hier zählen alle verfügbaren Risikobasen einschließlich Schätzungen. Eine historische Auswertung, keine Gewinnprognose.',
  },
  filteredMeanR: {
    title: 'Mittelwert der Netto-R',
    meaning: 'Der historische Erwartungswert für die hier ausgewählte Risikobasis.',
    calculation: 'Summe der gültigen Netto-R ÷ deren Anzahl. Der Risikofilter gilt; ausgeschlossene Werte zählen nicht als null.',
    reading: '+0,5 R heißt durchschnittlich ein halbes ursprüngliches Risiko Nettogewinn pro ausgewertetem Trade. Große Einzelgewinne oder -verluste können den Mittelwert stark verschieben. Deshalb auch Median und Verteilung betrachten; kein prognostizierter Gewinn.',
  },
  winRate: {
    title: 'Trefferquote',
    meaning: 'Anteil deiner abgeschlossenen Trades mit positivem Netto-Ergebnis.',
    calculation: 'Anzahl positiver Netto-Trades ÷ alle abgeschlossenen Trades × 100. Break-even zählt zum Nenner.',
    reading: '60 % heißt: 6 von 10 Trades waren nach erfassten Kosten positiv. Eine hohe Quote allein bedeutet nicht Profitabilität: Wenige große Verluste können viele kleine Gewinne aufheben.',
  },
  drawdown: {
    title: 'Rückgang vom Kontohöchststand',
    meaning: 'Zeigt, wie weit der realisierte Kontostand unter einem zuvor erreichten Hoch liegt.',
    calculation: '(Bisheriger Höchststand − aktueller Kontostand) ÷ Höchststand × 100. „Max. Rückgang“ ist der größte dieser Werte im Zeitraum; Startkapital zählt als erstes Hoch.',
    reading: '10 % heißt z. B. ein Rückgang von 10.000 € auf 9.000 €. Kein größter Einzelverlust und keine Obergrenze künftiger Verluste. Reihenfolge nach Einstieg; offene Positionen fehlen. Prozentwerte setzen positive Höchststände voraus.',
  },
  profitFactor: {
    title: 'Profitfaktor',
    meaning: 'Vergleicht die Summe deiner Nettogewinne mit der Summe deiner Nettoverluste.',
    calculation: 'Summe positiver Netto-Ergebnisse ÷ Betrag der Summe negativer Netto-Ergebnisse.',
    reading: '1,5 bedeutet 1,50 € Gewinn je 1 € Verlust, also insgesamt positiv. Unter 1 überwiegen die Verluste. Bei Gewinnen ohne Verluste erscheint ∞: Das ist keine nachgewiesene Sicherheit, sondern ein fehlender Nenner. Bei nur Null-Ergebnissen zeigt die App 0.',
  },
  payoffRatio: {
    title: 'Gewinn-Verlust-Verhältnis',
    meaning: 'Vergleicht die Größe eines durchschnittlichen Gewinners mit der eines durchschnittlichen Verlierers.',
    calculation: 'Durchschnittlicher positiver Netto-Trade ÷ Betrag des durchschnittlichen negativen Netto-Trades. Break-even gehört zu keiner der beiden Gruppen.',
    reading: '2 bedeutet: Ein Gewinner ist im Schnitt doppelt so groß wie ein Verlierer. Das unterscheidet sich vom Profitfaktor, weil die Häufigkeit der Gewinne hier nicht eingeht. Gewinne ohne Verluste ergeben ∞; zusammen mit der Trefferquote lesen.',
  },
  expectancyEUR: {
    title: 'Erwartungswert in EUR',
    meaning: 'Dein bisheriges durchschnittliches Netto-Ergebnis je abgeschlossenem Trade.',
    calculation: 'Netto-Ergebnis aller ausgewählten Trades ÷ deren Anzahl, einschließlich Break-even und Trades ohne Risikobasis.',
    reading: '+25 € heißt im Schnitt 25 € Nettogewinn pro Trade, nicht 25 € Gewinn beim nächsten Trade. Unterschiedliche Positionsgrößen beeinflussen diesen Wert; R setzt das Ergebnis zusätzlich ins Verhältnis zum Risiko.',
  },
  fees: {
    title: 'Erfasste Kosten',
    meaning: 'Die Kosten, die vom Brutto-Ergebnis abgezogen wurden.',
    calculation: 'Summe hinterlegter Ordergebühren und Swap plus Gewinnbeteiligung. Je positivem Brutto-Trade: Bruttogewinn × Beteiligungssatz ÷ 100.',
    reading: '100 € bedeuten, dass das Netto-Ergebnis 100 € unter dem Brutto-Ergebnis liegt. Keine vollständige Kostenprüfung: Nicht eingetragene Kosten fehlen; bereits im Brutto-Ergebnis enthaltene Kosten nicht doppelt eintragen.',
  },
  avgWin: {
    title: 'Durchschnittlicher Gewinn',
    meaning: 'Durchschnittlicher Netto-Ertrag deiner profitablen Trades.',
    calculation: 'Summe positiver Netto-Ergebnisse ÷ Anzahl positiver Netto-Trades.',
    reading: '+100 € heißt, dass ein Gewinner im Schnitt 100 € gebracht hat. Verluste und Break-even zählen hier nicht mit. Der Wert sagt allein weder etwas über die Trefferquote noch die Gesamtprofitabilität aus.',
  },
  avgLoss: {
    title: 'Durchschnittlicher Verlust',
    meaning: 'Durchschnittliches Netto-Ergebnis deiner verlustreichen Trades.',
    calculation: 'Summe negativer Netto-Ergebnisse ÷ Anzahl negativer Netto-Trades.',
    reading: '−100 € bedeutet im Schnitt 100 € Verlust pro Verlierer. Gewinne und Break-even zählen nicht mit. Erfasste Kosten sind enthalten; das ist weder ein geplanter Stop-Loss noch eine Verlustgrenze.',
  },
  winStreak: {
    title: 'Längste Gewinnserie',
    meaning: 'Die längste Folge profitabler Trades innerhalb der Auswahl.',
    calculation: 'Trades nach Einstiegsdatum und -zeit ordnen und aufeinanderfolgende positive Netto-Ergebnisse zählen. Ein Verlust oder Break-even unterbricht die Serie.',
    reading: '5 bedeutet fünf Gewinner direkt hintereinander. Keine Aussage darüber, ob der nächste Trade gewinnt. Ohne separate Abschlusszeiten kann die Reihenfolge von der tatsächlichen Realisierung abweichen.',
  },
  lossStreak: {
    title: 'Längste Verlustserie',
    meaning: 'Die längste Folge verlustreicher Trades innerhalb der Auswahl.',
    calculation: 'Trades nach Einstiegsdatum und -zeit ordnen und aufeinanderfolgende negative Netto-Ergebnisse zählen. Ein Gewinn oder Break-even unterbricht die Serie.',
    reading: '4 bedeutet vier Verlierer direkt hintereinander. Künftige Serien können länger sein. Ohne separate Abschlusszeiten kann die Reihenfolge von der tatsächlichen Realisierung abweichen.',
  },
  medianR: {
    title: 'Median der Netto-R',
    meaning: 'Der mittlere Wert deiner geordneten Ergebnisse, weniger empfindlich gegenüber einzelnen Extremwerten als der Durchschnitt.',
    calculation: 'Gültige Netto-R der gewählten Risikobasis sortieren und den mittleren Wert nehmen; bei gerader Anzahl die zwei mittleren Werte mitteln.',
    reading: 'Bei −1 R, +0,5 R und +5 R ist der Median +0,5 R, der Mittelwert +1,5 R. So wird sichtbar, ob einzelne Ausreißer den Durchschnitt prägen. Ein positiver Median garantiert kein positives Gesamtergebnis.',
  },
  rolling: {
    title: 'Gleitender Erwartungswert',
    meaning: 'Zeigt, wie sich dein durchschnittliches Netto-R über aufeinanderfolgende Abschnitte entwickelt.',
    calculation: 'Je Punkt die letzten 20 bzw. 50 Trades im gewählten Zeitraum betrachten und deren gültige Netto-R mitteln. Reihenfolge nach Einstieg; erst vollständige Fenster zeigen einen Wert.',
    reading: 'Über null waren die auswertbaren Trades des Fensters im Mittel positiv, darunter negativ. Fehlende R-Werte werden nicht durch ältere Trades ersetzt. Fenster überlappen; ein Anstieg beweist weder eine Verbesserung der Strategie noch künftige Gewinne.',
  },
  coverage: {
    title: 'R-Abdeckung',
    meaning: 'Zeigt, wie viele Trades tatsächlich in eine R-Auswertung eingehen.',
    calculation: 'Anzahl gültiger Netto-R gemäß Risikofilter gegenüber allen Trades des Fensters bzw. der Vergleichsgruppe.',
    reading: '12 / 20 bedeutet: 12 Trades ausgewertet, 8 ohne verwendbare Risikobasis oder durch den Filter ausgeschlossen. Das Ergebnis beschreibt nur diese Teilmenge. Hohe Abdeckung ist kein Beleg für korrekte Risikowerte.',
  },
  totalCoverage: {
    title: 'Trades mit Risikobasis',
    meaning: 'Zeigt, welcher Teil aller ausgewählten Trades in die übergeordneten R-Kennzahlen eingeht.',
    calculation: 'Anzahl Trades mit gültigem Netto-R gegenüber allen Trades im Zeitraum. Gespeicherte, rekonstruierte und geschätzte Risikobasen zählen; der lokale R-Analysefilter gilt hier nicht.',
    reading: '12 / 20 bedeutet, dass die R-Kennzahlen nur 12 der 20 Trades beschreiben. Fehlende Werte sind keine Null-Ergebnisse. Vollständigkeit allein sagt nichts über die Richtigkeit der Risikowerte aus.',
  },
  distribution: {
    title: 'Verteilung der Netto-R',
    meaning: 'Zeigt, ob deine Ergebnisse eng beieinanderliegen oder von wenigen großen Gewinnen und Verlusten geprägt sind.',
    calculation: 'Gültige Netto-R gemäß Risikofilter in die angegebenen Bereiche einteilen und Trades pro Bereich zählen. 0 R erhält einen eigenen Bereich; die Randbereiche enthalten auch extreme Werte.',
    reading: 'Horizontal steht das Ergebnis in R, vertikal die Trade-Anzahl. Hohe Balken sind häufig, nicht automatisch profitabel. Alle Werte sind nach erfassten Kosten; fehlendes Risiko ist kein Break-even.',
  },
  quartiles: {
    title: 'Mittlere 50 % der Netto-R',
    meaning: 'Der Bereich zwischen unterem und oberem Quartil beschreibt die Streuung im mittleren Teil der Daten.',
    calculation: 'Gültige Netto-R sortieren. Die Positionen (Anzahl − 1) × 0,25 und × 0,75 bestimmen; zwischen benachbarten Werten linear interpolieren.',
    reading: '−1 R bis +2 R zeigt einen breiten mittleren Ergebnisbereich. Werte außerhalb werden nicht entfernt. Bei kleinen Stichproben sind Quartile interpolierte Schwellen, kein Vorhersageintervall für zukünftige Trades.',
  },
  reviewComparison: {
    title: 'Regeltreue und Ergebnisse',
    meaning: 'Vergleicht Ergebnisse nach deiner eigenen Einschätzung, ob Setup oder geplantes Risiko eingehalten wurden.',
    calculation: 'Nur abgeschlossene Reviews nach Antwort gruppieren. Netto EUR summiert alle Gruppenergebnisse; Ø R und Median nutzen nur die gültigen R-Werte gemäß Risikofilter.',
    reading: 'Unterschiede sind Anhaltspunkte für deinen Review, kein Beweis, dass Regelbruch Gewinn oder Verlust verursacht. Gruppengröße und R-Abdeckung beachten. Offene Reviews fehlen; „nicht bewertet“ und „nicht anwendbar“ sind keine Regelverstöße.',
  },
  totalR: {
    title: 'Netto-R gesamt',
    meaning: 'Addiert die risikobezogenen Ergebnisse deiner auswertbaren Trades.',
    calculation: 'Je Trade Netto-Ergebnis ÷ ursprüngliches Geldrisiko berechnen, dann alle verfügbaren Netto-R einschließlich Rekonstruktionen und Schätzungen summieren.',
    reading: '+10 R ist die Summe einzelner R-Ergebnisse, nicht 10 % Kontorendite und bei wechselndem Risiko auch kein fester Euro-Betrag. Viele Trades können die Summe erhöhen; zum Vergleich zusätzlich den Mittelwert betrachten.',
  },
  meanRisk: {
    title: 'Durchschnittliches Geldrisiko',
    meaning: 'Mittlere verfügbare Geldrisikobasis je Trade, nicht durchschnittlicher tatsächlicher Verlust.',
    calculation: 'Summe verfügbarer Geldrisiken ÷ Anzahl dieser Werte. Gespeicherte, rekonstruierte und geschätzte Werte zählen; fehlende Werte nicht.',
    reading: '100 € bedeutet durchschnittlich 100 € als ursprüngliches Risiko angesetzt. Das ist weder eine Empfehlung zur Positionsgröße noch eine sichere Verlustgrenze. Stop-Ausführung und tatsächliche Verluste können abweichen.',
  },
  wilson: {
    title: '95-%-Wilson-Intervall',
    meaning: 'Beschreibt die statistische Unsicherheit der beobachteten Trefferquote.',
    calculation: 'p = Gewinner ÷ Trades, n = Trade-Anzahl, z = 1,96. Grenzen: [p + z²/(2n) ± z × √(p(1−p)/n + z²/(4n²))] ÷ [1 + z²/n], als Prozent.',
    reading: 'Unter unabhängigen, vergleichbaren Trades würden bei vielen Wiederholungen ungefähr 95 % solcher Intervalle die zugrunde liegende Trefferquote enthalten. Kein garantierter Bereich der nächsten Ergebnisse und kein Intervall für den R-Erwartungswert. Abhängige Trades oder wechselnde Strategien schwächen diese Aussage.',
  },
  balance: {
    title: 'Realisierter Kapitalverlauf',
    meaning: 'Zeigt, wie die erfassten abgeschlossenen Trades den Kontostand verändert haben.',
    calculation: 'Kapital am Zeitraumstart plus fortlaufende Summe der Netto-Ergebnisse. Reihenfolge nach Einstiegsdatum und -zeit.',
    reading: 'Eine steigende Stufe steht für Nettogewinn, eine fallende für Nettoverlust. Anders als eine vollständige Equity-Kurve enthält diese Kurve keine offenen Positionen. Fehlende Ein- oder Auszahlungen sowie abweichende Abschlussreihenfolgen können den tatsächlichen Kontoverlauf verändern.',
  },
  ranking: {
    title: 'Ergebnisse je Gruppe',
    meaning: 'Vergleicht die erfassten Trades nach Markt, Setup oder Wochentag.',
    calculation: 'Je Gruppe Netto-Ergebnisse summieren, positive Netto-Trades durch alle Gruppentrades teilen und gültige Netto-R mitteln. Hier zählen alle verfügbaren Risikobasen, unabhängig vom Filter der R-Analyse.',
    reading: 'Ein hoher Euro-Gewinn kann aus mehr Trades oder größeren Positionen entstehen, nicht nur aus einem besseren Setup. Trade-Anzahl und durchschnittliches R gemeinsam lesen. Kleine oder unterschiedliche Gruppen sind nur eingeschränkt vergleichbar.',
  },
  risk_stored: {
    title: 'Gespeichertes Geldrisiko',
    meaning: 'Im Trade ist ein positiver ursprünglicher Risikobetrag hinterlegt.',
    calculation: 'Dieser Betrag wird direkt als Nenner verwendet: Netto-Ergebnis ÷ gespeichertes Geldrisiko.',
    reading: 'Bei 100 € Risiko und 50 € Nettogewinn entstehen +0,5 R. „Gespeichert“ beschreibt die Herkunft, nicht die Richtigkeit: Ein manueller Wert ist nicht unabhängig geprüft.',
  },
  risk_reconstructed: {
    title: 'Rekonstruiertes Geldrisiko',
    meaning: 'Das Geldrisiko wurde aus älteren Trade-Angaben abgeleitet, nicht direkt gespeichert.',
    calculation: 'Brutto-Ergebnis ÷ erfasstes Brutto-R, sofern daraus ein positiver endlicher Risikobetrag entsteht.',
    reading: '200 € Bruttogewinn bei +2 R ergeben 100 € Geldrisiko. Danach wird Netto-R nach erfassten Kosten berechnet. Fehler im Brutto-Ergebnis oder im erfassten R wirken auf diese Rekonstruktion durch.',
  },
  risk_estimated: {
    title: 'Geschätztes Geldrisiko',
    meaning: 'Es fehlen ein gespeichertes Geldrisiko und eine verwendbare Rekonstruktion.',
    calculation: 'Hinterlegtes Kontostartkapital × Stop-Loss-Prozentsatz ÷ 100.',
    reading: '10.000 € Startkapital bei 1 % ergeben eine Schätzung von 100 €. Weicht das tatsächliche Kapital bei Eröffnung ab, kann diese Risikobasis falsch sein. Für strengere R-Auswertungen lassen sich Schätzungen ausschließen.',
  },
  risk_missing: {
    title: 'Fehlende Risikobasis',
    meaning: 'Es gibt keinen positiven, verwendbaren Geldrisikowert für diesen Trade.',
    calculation: 'Ohne gültigen Nenner wird kein Netto-R berechnet. Der Trade bleibt in Euro-Ergebnis und Trade-Anzahl enthalten.',
    reading: '„—“ heißt nicht 0 R und nicht Break-even. R-Mittelwerte und Verteilungen beschreiben dann nur die verbleibenden Trades; ein ergänztes ursprüngliches Risiko kann diese Auswertungen verändern.',
  },
};

export const metricHelpKeys = {
  'Netto-Ergebnis': 'netPnl', 'Erwartungswert': 'expectancyR', 'Trefferquote': 'winRate', 'Max. Rückgang': 'drawdown',
  'Profitfaktor': 'profitFactor', 'Gewinn-Verlust-Verhältnis': 'payoffRatio', 'Erwartungswert in EUR': 'expectancyEUR',
  'Erfasste Kosten': 'fees', 'Ø Gewinn': 'avgWin', 'Ø Verlust': 'avgLoss', 'Längste Gewinnserie': 'winStreak', 'Längste Verlustserie': 'lossStreak',
  'Median': 'medianR', 'Mittelwert': 'filteredMeanR', 'Letztes Fenster': 'rolling', 'R-Abdeckung': 'coverage',
};
